"""add onboarding_profiles table and onboarding flag

Revision ID: 6fdd8400c90c
Revises: 74280c319e03
Create Date: 2025-12-18 13:47:49.145888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fdd8400c90c'
down_revision: Union[str, Sequence[str], None] = '74280c319e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.alter_column("users", "has_completed_onboarding", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_onboarding')
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###
